spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.116.53.24:3306/citadel
    username: ryan
    password: ryanpsw
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0